In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

In [2]:
img1= cv2.imread('dog.jpg',0)
print(img1)

[[ 35  26  18 ...  42  43  44]
 [ 38  31  24 ...  44  45  46]
 [ 41  36  30 ...  45  45  46]
 ...
 [ 23  23  24 ... 108 106 105]
 [ 23  23  24 ... 108 106 105]
 [ 23  23  24 ... 108 107 105]]


In [5]:
img2=cv2.resize(img1,(512,512))
print(img2)

[[ 30  14  12 ...  42  42  45]
 [ 32  14  14 ...  42  42  40]
 [ 34  22  16 ...  42  41  42]
 ...
 [ 32  35  38 ... 101 103 104]
 [ 27  33  38 ... 107 103 102]
 [ 23  29  33 ... 112 111 106]]


In [6]:
im3=cv2.resize(img2,(1803,1803))
print(im3)

[[ 30  30  27 ...  44  45  45]
 [ 30  30  26 ...  44  45  45]
 [ 30  30  27 ...  43  44  44]
 ...
 [ 24  24  25 ... 106 105 105]
 [ 23  23  24 ... 107 106 106]
 [ 23  23  24 ... 107 106 106]]
